packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@eslint/js': ^9.39.0
  '@next/eslint-plugin-next': ^15.4.2
  '@prisma/adapter-pg': ^7.0.1
  '@prisma/client': ^7.0.0
  '@react-email/components': ^1
  '@react-email/render': ^1.4.0
  '@tailwindcss/postcss': ^4.1.11
  '@tanstack/react-form': 1.23.8
  '@tanstack/react-query': ^5.90.10
  '@trpc/client': ^11.7.1
  '@trpc/react-query': ^11.7.1
  '@trpc/server': ^11.7.1
  '@trpc/tanstack-react-query': ^11.7.1
  '@types/node': ^20
  '@types/react': ^19
  '@types/react-dom': ^19
  babel-plugin-react-compiler: 1.0.0
  better-auth: ^1.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.39.0
  eslint-config-next: ^16.0.3
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.6.0
  globals: ^16.5.0
  hono: ^4.10.4
  lucide-react: ^0.475.0
  next: ^15.5.0
  next-themes: ^0.4.6
  pg: ^8.16.3
  postcss: ^8.5.3
  prisma: ^7.0.0
  react: '>=19.1.0 <19.2.0'
  react-dom: '>=19.1.0 <19.2.0'
  react-email: ^5
  resend: ^4.0.0
  server-only: ^0.0.1
  superjson: ^2.2.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  typescript: ^5
  typescript-eslint: ^8.46.2
  zod: ^4.1.0

catalogs:
  native:
    '@types/react': ~19.1.0
    '@types/react-dom': ~19.1.0
    expo: ~54.0.25
    lightningcss: 1.30.1
    nativewind: 5.0.0-preview.2
    react: 19.1.0
    react-dom: 19.1.0
    react-native: 0.81.5
    react-native-reanimated: ~4.1.3
    react-native-safe-area-context: ~5.6.1
    tailwindcss-animate: ^1.0.7
  next16:
    '@next/eslint-plugin-next': ^16.0.0
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    babel-plugin-react-compiler: ^1.0.0
    eslint-config-next: ^16.0.0
    next: ^16.0.0
    react: ^19.2.0
    react-dom: ^19.2.0

nodeLinker: hoisted

settings:
  catalogMode: warn
