// @generated by packages/styles/scripts/gen-tokens.ts
// DO NOT EDIT MANUALLY - Source: packages/styles/tokens.css

export type ColorToken = {
  original: string;
  hex: string;
  p3: string;
};

export const TOKENS = {
  light: {
  "background": {
    "original": "oklch(0.9195 0.0655 88.9829)",
    "hex": "#f6e3b3",
    "p3": "color(display-p3 0.952001947352971 0.8927879762776284 0.7232888330432502)"
  },
  "foreground": {
    "original": "oklch(0.3242 0.0189 63.7285)",
    "hex": "#3b322a",
    "p3": "color(display-p3 0.2255497871464403 0.1973391112242548 0.16850915041597236)"
  },
  "card": {
    "original": "oklch(0.9407 0.0751 89.9024)",
    "hex": "#ffeab2",
    "p3": "color(display-p3 0.9860026341153451 0.9205150958920497 0.7234047652483693)"
  },
  "card-foreground": {
    "original": "oklch(0.3242 0.0189 63.7285)",
    "hex": "#3b322a",
    "p3": "color(display-p3 0.2255497871464403 0.1973391112242548 0.16850915041597236)"
  },
  "popover": {
    "original": "oklch(0.9114 0.1024 87.1814)",
    "hex": "#ffde91",
    "p3": "color(display-p3 0.9787050263099405 0.8753229921350288 0.6078344185046359)"
  },
  "popover-foreground": {
    "original": "oklch(0.3242 0.0189 63.7285)",
    "hex": "#3b322a",
    "p3": "color(display-p3 0.2255497871464403 0.1973391112242548 0.16850915041597236)"
  },
  "primary": {
    "original": "oklch(0.414 0.0676 63.9833)",
    "hex": "#654321",
    "p3": "color(display-p3 0.376488713291363 0.26846985330303946 0.15231377835318083)"
  },
  "primary-foreground": {
    "original": "oklch(0.9637 0.0416 87.3639)",
    "hex": "#fff2d4",
    "p3": "color(display-p3 0.9912386083783878 0.9507955839873429 0.8438414011893449)"
  },
  "secondary": {
    "original": "oklch(0.3202 0.0572 150.2191)",
    "hex": "#1b3b23",
    "p3": "color(display-p3 0.13711872057612093 0.22836921527148818 0.14580068215615333)"
  },
  "secondary-foreground": {
    "original": "oklch(0.9214 0.0914 87.4415)",
    "hex": "#ffe29e",
    "p3": "color(display-p3 0.9811386407745407 0.8904106384205732 0.652633734051758)"
  },
  "muted": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "muted-foreground": {
    "original": "oklch(0.462 0.0321 72.2978)",
    "hex": "#645645",
    "p3": "color(display-p3 0.38302120058956995 0.3392099371203652 0.2786472921303329)"
  },
  "accent": {
    "original": "oklch(0.9214 0.0914 87.4415)",
    "hex": "#ffe29e",
    "p3": "color(display-p3 0.9811386407745407 0.8904106384205732 0.652633734051758)"
  },
  "accent-foreground": {
    "original": "oklch(0.3242 0.0189 63.7285)",
    "hex": "#3b322a",
    "p3": "color(display-p3 0.2255497871464403 0.1973391112242548 0.16850915041597236)"
  },
  "destructive": {
    "original": "oklch(0.4667 0.1205 32.9445)",
    "hex": "#913b2a",
    "p3": "color(display-p3 0.5277473519315625 0.25198477129700697 0.186589788711625)"
  },
  "destructive-foreground": {
    "original": "oklch(1 0 0)",
    "hex": "#ffffff",
    "p3": "color(display-p3 1 1 1)"
  },
  "border": {
    "original": "oklch(0.5265 0.0647 64.8006)",
    "hex": "#856342",
    "p3": "color(display-p3 0.5011326753658425 0.39358250565638775 0.27758629050723205)"
  },
  "input": {
    "original": "oklch(0.7509 0.0573 84.9673)",
    "hex": "#bfac85",
    "p3": "color(display-p3 0.7364971916482786 0.6771276096006686 0.5393116082500916)"
  },
  "ring": {
    "original": "oklch(0.5265 0.0647 64.8006)",
    "hex": "#856342",
    "p3": "color(display-p3 0.5011326753658425 0.39358250565638775 0.27758629050723205)"
  },
  "chart-1": {
    "original": "oklch(0.5265 0.0647 64.8006)",
    "hex": "#856342",
    "p3": "color(display-p3 0.5011326753658425 0.39358250565638775 0.27758629050723205)"
  },
  "chart-2": {
    "original": "oklch(0.479 0.0519 68.2251)",
    "hex": "#71583d",
    "p3": "color(display-p3 0.4276636367067036 0.34890035412873727 0.25379406627998885)"
  },
  "chart-3": {
    "original": "oklch(0.416 0.0479 73.1705)",
    "hex": "#5c482e",
    "p3": "color(display-p3 0.34836836939089344 0.2854069433665746 0.19455179458152552)"
  },
  "chart-4": {
    "original": "oklch(0.5838 0.068 64.2666)",
    "hex": "#987350",
    "p3": "color(display-p3 0.5737620647688223 0.45676222151596485 0.33321465680426526)"
  },
  "chart-5": {
    "original": "oklch(0.6321 0.0792 65.5619)",
    "hex": "#ab8055",
    "p3": "color(display-p3 0.644733565903812 0.5087630395082647 0.358030447238155)"
  },
  "sidebar": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "sidebar-foreground": {
    "original": "oklch(0.3242 0.0189 63.7285)",
    "hex": "#3b322a",
    "p3": "color(display-p3 0.2255497871464403 0.1973391112242548 0.16850915041597236)"
  },
  "sidebar-primary": {
    "original": "oklch(0.5265 0.0647 64.8006)",
    "hex": "#856342",
    "p3": "color(display-p3 0.5011326753658425 0.39358250565638775 0.27758629050723205)"
  },
  "sidebar-primary-foreground": {
    "original": "oklch(1 0 0)",
    "hex": "#ffffff",
    "p3": "color(display-p3 1 1 1)"
  },
  "sidebar-accent": {
    "original": "oklch(0.7332 0.0681 88.8921)",
    "hex": "#baa777",
    "p3": "color(display-p3 0.7169382063465864 0.657599524451194 0.48947518749043567)"
  },
  "sidebar-accent-foreground": {
    "original": "oklch(0.3242 0.0189 63.7285)",
    "hex": "#3b322a",
    "p3": "color(display-p3 0.2255497871464403 0.1973391112242548 0.16850915041597236)"
  },
  "sidebar-border": {
    "original": "oklch(0.7509 0.0573 84.9673)",
    "hex": "#bfac85",
    "p3": "color(display-p3 0.7364971916482786 0.6771276096006686 0.5393116082500916)"
  },
  "sidebar-ring": {
    "original": "oklch(0.5265 0.0647 64.8006)",
    "hex": "#856342",
    "p3": "color(display-p3 0.5011326753658425 0.39358250565638775 0.27758629050723205)"
  },
  "font-sans": "Libre Baskerville, serif",
  "font-serif": "Lora, serif",
  "font-mono": "IBM Plex Mono, monospace",
  "radius": 0,
  "shadow-x": 2,
  "shadow-y": -1,
  "shadow-blur": 3,
  "shadow-spread": 0,
  "shadow-opacity": "0.6",
  "shadow-color": {
    "original": "#4a3924",
    "hex": "#4a3924",
    "p3": "color(display-p3 0.27969511213245957 0.2261078384385739 0.15254233617342108)"
  },
  "shadow-2xs": "2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.3)",
  "shadow-xs": "2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.3)",
  "shadow-sm": "2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6),\n    2px 1px 2px -1px hsl(33.1579 34.5455% 21.5686% / 0.6)",
  "shadow": "2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6),\n    2px 1px 2px -1px hsl(33.1579 34.5455% 21.5686% / 0.6)",
  "shadow-md": "2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6),\n    2px 2px 4px -1px hsl(33.1579 34.5455% 21.5686% / 0.6)",
  "shadow-lg": "2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6),\n    2px 4px 6px -1px hsl(33.1579 34.5455% 21.5686% / 0.6)",
  "shadow-xl": "2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6),\n    2px 8px 10px -1px hsl(33.1579 34.5455% 21.5686% / 0.6)",
  "shadow-2xl": "2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 1.5)",
  "tracking-normal": "-0.05em",
  "spacing": 4
},
  dark: {
  "background": {
    "original": "oklch(0.2405 0.012 55.7477)",
    "hex": "#241e1a",
    "p3": "color(display-p3 0.13730352256655493 0.11845180182572002 0.10385236289257105)"
  },
  "foreground": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "card": {
    "original": "oklch(0.2817 0.0126 62.0956)",
    "hex": "#2e2823",
    "p3": "color(display-p3 0.17639771855702546 0.15771434566311698 0.139692776244372)"
  },
  "card-foreground": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "popover": {
    "original": "oklch(0.2817 0.0126 62.0956)",
    "hex": "#2e2823",
    "p3": "color(display-p3 0.17639771855702546 0.15771434566311698 0.139692776244372)"
  },
  "popover-foreground": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "primary": {
    "original": "oklch(0.6321 0.0792 65.5619)",
    "hex": "#ab8055",
    "p3": "color(display-p3 0.644733565903812 0.5087630395082647 0.358030447238155)"
  },
  "primary-foreground": {
    "original": "oklch(0.2405 0.012 55.7477)",
    "hex": "#241e1a",
    "p3": "color(display-p3 0.13730352256655493 0.11845180182572002 0.10385236289257105)"
  },
  "secondary": {
    "original": "oklch(0.3279 0.0144 54.0632)",
    "hex": "#3b332e",
    "p3": "color(display-p3 0.22612575665105505 0.2011123957742199 0.1828777142079778)"
  },
  "secondary-foreground": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "muted": {
    "original": "oklch(0.2561 0.0106 60.9866)",
    "hex": "#27221e",
    "p3": "color(display-p3 0.14962968837348312 0.13399100080530382 0.11947597850333486)"
  },
  "muted-foreground": {
    "original": "oklch(0.6886 0.0377 81.1785)",
    "hex": "#a79981",
    "p3": "color(display-p3 0.6456057891961178 0.6019101609717119 0.5163346761320933)"
  },
  "accent": {
    "original": "oklch(0.3598 0.0228 53.3857)",
    "hex": "#473a32",
    "p3": "color(display-p3 0.2701552344019733 0.2293451938735545 0.20025542009758435)"
  },
  "accent-foreground": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "destructive": {
    "original": "oklch(0.4667 0.1205 32.9445)",
    "hex": "#913b2a",
    "p3": "color(display-p3 0.5277473519315625 0.25198477129700697 0.186589788711625)"
  },
  "destructive-foreground": {
    "original": "oklch(1 0 0)",
    "hex": "#ffffff",
    "p3": "color(display-p3 1 1 1)"
  },
  "border": {
    "original": "oklch(0.3279 0.0144 54.0632)",
    "hex": "#3b332e",
    "p3": "color(display-p3 0.22612575665105505 0.2011123957742199 0.1828777142079778)"
  },
  "input": {
    "original": "oklch(0.3279 0.0144 54.0632)",
    "hex": "#3b332e",
    "p3": "color(display-p3 0.22612575665105505 0.2011123957742199 0.1828777142079778)"
  },
  "ring": {
    "original": "oklch(0.6321 0.0792 65.5619)",
    "hex": "#ab8055",
    "p3": "color(display-p3 0.644733565903812 0.5087630395082647 0.358030447238155)"
  },
  "chart-1": {
    "original": "oklch(0.6321 0.0792 65.5619)",
    "hex": "#ab8055",
    "p3": "color(display-p3 0.644733565903812 0.5087630395082647 0.358030447238155)"
  },
  "chart-2": {
    "original": "oklch(0.5838 0.068 64.2666)",
    "hex": "#987350",
    "p3": "color(display-p3 0.5737620647688223 0.45676222151596485 0.33321465680426526)"
  },
  "chart-3": {
    "original": "oklch(0.5265 0.0647 64.8006)",
    "hex": "#856342",
    "p3": "color(display-p3 0.5011326753658425 0.39358250565638775 0.27758629050723205)"
  },
  "chart-4": {
    "original": "oklch(0.479 0.0519 68.2251)",
    "hex": "#71583d",
    "p3": "color(display-p3 0.4276636367067036 0.34890035412873727 0.25379406627998885)"
  },
  "chart-5": {
    "original": "oklch(0.416 0.0479 73.1705)",
    "hex": "#5c482e",
    "p3": "color(display-p3 0.34836836939089344 0.2854069433665746 0.19455179458152552)"
  },
  "sidebar": {
    "original": "oklch(0.2405 0.012 55.7477)",
    "hex": "#241e1a",
    "p3": "color(display-p3 0.13730352256655493 0.11845180182572002 0.10385236289257105)"
  },
  "sidebar-foreground": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "sidebar-primary": {
    "original": "oklch(0.6321 0.0792 65.5619)",
    "hex": "#ab8055",
    "p3": "color(display-p3 0.644733565903812 0.5087630395082647 0.358030447238155)"
  },
  "sidebar-primary-foreground": {
    "original": "oklch(0.2405 0.012 55.7477)",
    "hex": "#241e1a",
    "p3": "color(display-p3 0.13730352256655493 0.11845180182572002 0.10385236289257105)"
  },
  "sidebar-accent": {
    "original": "oklch(0.3598 0.0228 53.3857)",
    "hex": "#473a32",
    "p3": "color(display-p3 0.2701552344019733 0.2293451938735545 0.20025542009758435)"
  },
  "sidebar-accent-foreground": {
    "original": "oklch(0.8018 0.0491 82.6475)",
    "hex": "#cebc9b",
    "p3": "color(display-p3 0.7958948973420075 0.7396831666524848 0.6223102340922525)"
  },
  "sidebar-border": {
    "original": "oklch(0.3279 0.0144 54.0632)",
    "hex": "#3b332e",
    "p3": "color(display-p3 0.22612575665105505 0.2011123957742199 0.1828777142079778)"
  },
  "sidebar-ring": {
    "original": "oklch(0.6321 0.0792 65.5619)",
    "hex": "#ab8055",
    "p3": "color(display-p3 0.644733565903812 0.5087630395082647 0.358030447238155)"
  },
  "font-sans": "Libre Baskerville, serif",
  "font-serif": "Lora, serif",
  "font-mono": "IBM Plex Mono, monospace",
  "radius": 0,
  "shadow-x": 2,
  "shadow-y": -1,
  "shadow-blur": 3,
  "shadow-spread": 0,
  "shadow-opacity": "0.6",
  "shadow-color": {
    "original": "#ab8055",
    "hex": "#ab8055",
    "p3": "color(display-p3 0.6447217425895295 0.5087327020843585 0.3579780259637712)"
  },
  "shadow-2xs": "2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.3)",
  "shadow-xs": "2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.3)",
  "shadow-sm": "2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6),\n    2px 1px 2px -1px hsl(30 33.8583% 50.1961% / 0.6)",
  "shadow": "2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6),\n    2px 1px 2px -1px hsl(30 33.8583% 50.1961% / 0.6)",
  "shadow-md": "2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6),\n    2px 2px 4px -1px hsl(30 33.8583% 50.1961% / 0.6)",
  "shadow-lg": "2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6),\n    2px 4px 6px -1px hsl(30 33.8583% 50.1961% / 0.6)",
  "shadow-xl": "2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6),\n    2px 8px 10px -1px hsl(30 33.8583% 50.1961% / 0.6)",
  "shadow-2xl": "2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 1.5)"
},
} as const;

export type LightTheme = typeof TOKENS.light;
export type DarkTheme = typeof TOKENS.dark;

/**
 * TYPE MAGIC:
 * Extracts ONLY the keys from the theme that are ColorTokens.
 * Excludes numbers (radius) and strings (fonts).
 */
export type ThemeColors = {
  [K in keyof LightTheme]: LightTheme[K] extends ColorToken ? K : never
}[keyof LightTheme];
