// @generated by packages/styles/scripts/gen-tokens.mjs
// DO NOT EDIT MANUALLY - Source: packages/styles/tokens.css

export type ColorToken = {
  original: string;
  hex: string;
  p3: string;
};

export const TOKENS = {
  light: {
    background: {
      original: 'oklch(0.9195 0.0655 88.9829)',
      hex: '#f6e3b3',
      p3: 'color(display-p3 0.952001968753487 0.8927879657638728 0.7232887310006725)',
    },
    foreground: {
      original: 'oklch(0.3242 0.0189 63.7285)',
      hex: '#3b322a',
      p3: 'color(display-p3 0.22554979230416805 0.19733910874459898 0.16850912356265302)',
    },
    card: {
      original: 'oklch(0.9407 0.0751 89.9024)',
      hex: '#ffeab2',
      p3: 'color(display-p3 0.9860026562534167 0.9205150846072068 0.7234046587400298)',
    },
    'card-foreground': {
      original: 'oklch(0.3242 0.0189 63.7285)',
      hex: '#3b322a',
      p3: 'color(display-p3 0.22554979230416805 0.19733910874459898 0.16850912356265302)',
    },
    popover: {
      original: 'oklch(0.9114 0.1024 87.1814)',
      hex: '#ffde91',
      p3: 'color(display-p3 0.9787050470314803 0.875322979789107 0.607834309093005)',
    },
    'popover-foreground': {
      original: 'oklch(0.3242 0.0189 63.7285)',
      hex: '#3b322a',
      p3: 'color(display-p3 0.22554979230416805 0.19733910874459898 0.16850912356265302)',
    },
    primary: {
      original: 'oklch(0.414 0.0676 63.9833)',
      hex: '#654321',
      p3: 'color(display-p3 0.37648871895023145 0.26846984845221317 0.15231373327420727)',
    },
    'primary-foreground': {
      original: 'oklch(0.9637 0.0416 87.3639)',
      hex: '#fff2d4',
      p3: 'color(display-p3 0.991238630936479 0.95079557441775 0.8438412970371628)',
    },
    secondary: {
      original: 'oklch(0.3202 0.0572 150.2191)',
      hex: '#1b3b23',
      p3: 'color(display-p3 0.13711873298773672 0.22836921180136271 0.1458006531351959)',
    },
    'secondary-foreground': {
      original: 'oklch(0.9214 0.0914 87.4415)',
      hex: '#ffe29e',
      p3: 'color(display-p3 0.9811386619086021 0.8904106265261242 0.6526336264518124)',
    },
    muted: {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    'muted-foreground': {
      original: 'oklch(0.462 0.0321 72.2978)',
      hex: '#645645',
      p3: 'color(display-p3 0.3830212088247284 0.33920993291293494 0.27864724946932695)',
    },
    accent: {
      original: 'oklch(0.9214 0.0914 87.4415)',
      hex: '#ffe29e',
      p3: 'color(display-p3 0.9811386619086021 0.8904106265261242 0.6526336264518124)',
    },
    'accent-foreground': {
      original: 'oklch(0.3242 0.0189 63.7285)',
      hex: '#3b322a',
      p3: 'color(display-p3 0.22554979230416805 0.19733910874459898 0.16850912356265302)',
    },
    destructive: {
      original: 'oklch(0.4667 0.1205 32.9445)',
      hex: '#913b2a',
      p3: 'color(display-p3 0.5277473544847502 0.25198476726668884 0.18658973912722082)',
    },
    'destructive-foreground': {
      original: 'oklch(1 0 0)',
      hex: '#ffffff',
      p3: 'color(display-p3 1 1 1)',
    },
    border: {
      original: 'oklch(0.5265 0.0647 64.8006)',
      hex: '#856342',
      p3: 'color(display-p3 0.5011326837540998 0.3935824998114439 0.27758623607225263)',
    },
    input: {
      original: 'oklch(0.7509 0.0573 84.9673)',
      hex: '#bfac85',
      p3: 'color(display-p3 0.7364972078459932 0.6771276013107372 0.5393115285113558)',
    },
    ring: {
      original: 'oklch(0.5265 0.0647 64.8006)',
      hex: '#856342',
      p3: 'color(display-p3 0.5011326837540998 0.3935824998114439 0.27758623607225263)',
    },
    'chart-1': {
      original: 'oklch(0.5265 0.0647 64.8006)',
      hex: '#856342',
      p3: 'color(display-p3 0.5011326837540998 0.3935824998114439 0.27758623607225263)',
    },
    'chart-2': {
      original: 'oklch(0.479 0.0519 68.2251)',
      hex: '#71583d',
      p3: 'color(display-p3 0.4276636446008579 0.34890034908155987 0.25379401897738724)',
    },
    'chart-3': {
      original: 'oklch(0.416 0.0479 73.1705)',
      hex: '#5c482e',
      p3: 'color(display-p3 0.3483683762297931 0.2854069389185855 0.19455175397030738)',
    },
    'chart-4': {
      original: 'oklch(0.5838 0.068 64.2666)',
      hex: '#987350',
      p3: 'color(display-p3 0.5737620743897685 0.4567622150264968 0.33321459577130913)',
    },
    'chart-5': {
      original: 'oklch(0.6321 0.0792 65.5619)',
      hex: '#ab8055',
      p3: 'color(display-p3 0.6447335764718548 0.5087630320683908 0.35803037831729606)',
    },
    sidebar: {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    'sidebar-foreground': {
      original: 'oklch(0.3242 0.0189 63.7285)',
      hex: '#3b322a',
      p3: 'color(display-p3 0.22554979230416805 0.19733910874459898 0.16850912356265302)',
    },
    'sidebar-primary': {
      original: 'oklch(0.5265 0.0647 64.8006)',
      hex: '#856342',
      p3: 'color(display-p3 0.5011326837540998 0.3935824998114439 0.27758623607225263)',
    },
    'sidebar-primary-foreground': {
      original: 'oklch(1 0 0)',
      hex: '#ffffff',
      p3: 'color(display-p3 1 1 1)',
    },
    'sidebar-accent': {
      original: 'oklch(0.7332 0.0681 88.8921)',
      hex: '#baa777',
      p3: 'color(display-p3 0.7169382224292304 0.6575995157148715 0.4894751076143982)',
    },
    'sidebar-accent-foreground': {
      original: 'oklch(0.3242 0.0189 63.7285)',
      hex: '#3b322a',
      p3: 'color(display-p3 0.22554979230416805 0.19733910874459898 0.16850912356265302)',
    },
    'sidebar-border': {
      original: 'oklch(0.7509 0.0573 84.9673)',
      hex: '#bfac85',
      p3: 'color(display-p3 0.7364972078459932 0.6771276013107372 0.5393115285113558)',
    },
    'sidebar-ring': {
      original: 'oklch(0.5265 0.0647 64.8006)',
      hex: '#856342',
      p3: 'color(display-p3 0.5011326837540998 0.3935824998114439 0.27758623607225263)',
    },
    'font-sans': 'Libre Baskerville, serif',
    'font-serif': 'Lora, serif',
    'font-mono': 'IBM Plex Mono, monospace',
    radius: 0,
    'shadow-x': 2,
    'shadow-y': -1,
    'shadow-blur': 3,
    'shadow-spread': 0,
    'shadow-opacity': '0.6',
    'shadow-color': {
      original: '#4a3924',
      hex: '#4a3924',
      p3: 'color(display-p3 0.2796951121324594 0.22610783843857407 0.15254233617342106)',
    },
    'shadow-2xs': '2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.3)',
    'shadow-xs': '2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.3)',
    'shadow-sm':
      '2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6), 2px 1px 2px -1px\n    hsl(33.1579 34.5455% 21.5686% / 0.6)',
    shadow:
      '2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6), 2px 1px 2px -1px\n    hsl(33.1579 34.5455% 21.5686% / 0.6)',
    'shadow-md':
      '2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6), 2px 2px 4px -1px\n    hsl(33.1579 34.5455% 21.5686% / 0.6)',
    'shadow-lg':
      '2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6), 2px 4px 6px -1px\n    hsl(33.1579 34.5455% 21.5686% / 0.6)',
    'shadow-xl':
      '2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 0.6), 2px 8px 10px -1px\n    hsl(33.1579 34.5455% 21.5686% / 0.6)',
    'shadow-2xl': '2px -1px 3px 0px hsl(33.1579 34.5455% 21.5686% / 1.5)',
    'tracking-normal': '0em',
    spacing: 4,
  },
  dark: {
    background: {
      original: 'oklch(0.2405 0.012 55.7477)',
      hex: '#241e1a',
      p3: 'color(display-p3 0.13730352606790502 0.11845180023888263 0.10385234465947296)',
    },
    foreground: {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    card: {
      original: 'oklch(0.2817 0.0126 62.0956)',
      hex: '#2e2823',
      p3: 'color(display-p3 0.17639772297451986 0.15771434372247897 0.1396927540372247)',
    },
    'card-foreground': {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    popover: {
      original: 'oklch(0.2817 0.0126 62.0956)',
      hex: '#2e2823',
      p3: 'color(display-p3 0.17639772297451986 0.15771434372247897 0.1396927540372247)',
    },
    'popover-foreground': {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    primary: {
      original: 'oklch(0.6321 0.0792 65.5619)',
      hex: '#ab8055',
      p3: 'color(display-p3 0.6447335764718548 0.5087630320683908 0.35803037831729606)',
    },
    'primary-foreground': {
      original: 'oklch(0.2405 0.012 55.7477)',
      hex: '#241e1a',
      p3: 'color(display-p3 0.13730352606790502 0.11845180023888263 0.10385234465947296)',
    },
    secondary: {
      original: 'oklch(0.3279 0.0144 54.0632)',
      hex: '#3b332e',
      p3: 'color(display-p3 0.22612576185990674 0.20111239351207671 0.1828776875028797)',
    },
    'secondary-foreground': {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    muted: {
      original: 'oklch(0.2561 0.0106 60.9866)',
      hex: '#27221e',
      p3: 'color(display-p3 0.14962969230804032 0.13399099911684198 0.1194759588588801)',
    },
    'muted-foreground': {
      original: 'oklch(0.6886 0.0377 81.1785)',
      hex: '#a79981',
      p3: 'color(display-p3 0.6456058035877726 0.6019101543456559 0.5163346068645499)',
    },
    accent: {
      original: 'oklch(0.3598 0.0228 53.3857)',
      hex: '#473a32',
      p3: 'color(display-p3 0.27015523993880347 0.22934519113813445 0.20025538964003348)',
    },
    'accent-foreground': {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    destructive: {
      original: 'oklch(0.4667 0.1205 32.9445)',
      hex: '#913b2a',
      p3: 'color(display-p3 0.5277473544847502 0.25198476726668884 0.18658973912722082)',
    },
    'destructive-foreground': {
      original: 'oklch(1 0 0)',
      hex: '#ffffff',
      p3: 'color(display-p3 1 1 1)',
    },
    border: {
      original: 'oklch(0.3279 0.0144 54.0632)',
      hex: '#3b332e',
      p3: 'color(display-p3 0.22612576185990674 0.20111239351207671 0.1828776875028797)',
    },
    input: {
      original: 'oklch(0.3279 0.0144 54.0632)',
      hex: '#3b332e',
      p3: 'color(display-p3 0.22612576185990674 0.20111239351207671 0.1828776875028797)',
    },
    ring: {
      original: 'oklch(0.6321 0.0792 65.5619)',
      hex: '#ab8055',
      p3: 'color(display-p3 0.6447335764718548 0.5087630320683908 0.35803037831729606)',
    },
    'chart-1': {
      original: 'oklch(0.6321 0.0792 65.5619)',
      hex: '#ab8055',
      p3: 'color(display-p3 0.6447335764718548 0.5087630320683908 0.35803037831729606)',
    },
    'chart-2': {
      original: 'oklch(0.5838 0.068 64.2666)',
      hex: '#987350',
      p3: 'color(display-p3 0.5737620743897685 0.4567622150264968 0.33321459577130913)',
    },
    'chart-3': {
      original: 'oklch(0.5265 0.0647 64.8006)',
      hex: '#856342',
      p3: 'color(display-p3 0.5011326837540998 0.3935824998114439 0.27758623607225263)',
    },
    'chart-4': {
      original: 'oklch(0.479 0.0519 68.2251)',
      hex: '#71583d',
      p3: 'color(display-p3 0.4276636446008579 0.34890034908155987 0.25379401897738724)',
    },
    'chart-5': {
      original: 'oklch(0.416 0.0479 73.1705)',
      hex: '#5c482e',
      p3: 'color(display-p3 0.3483683762297931 0.2854069389185855 0.19455175397030738)',
    },
    sidebar: {
      original: 'oklch(0.2405 0.012 55.7477)',
      hex: '#241e1a',
      p3: 'color(display-p3 0.13730352606790502 0.11845180023888263 0.10385234465947296)',
    },
    'sidebar-foreground': {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    'sidebar-primary': {
      original: 'oklch(0.6321 0.0792 65.5619)',
      hex: '#ab8055',
      p3: 'color(display-p3 0.6447335764718548 0.5087630320683908 0.35803037831729606)',
    },
    'sidebar-primary-foreground': {
      original: 'oklch(0.2405 0.012 55.7477)',
      hex: '#241e1a',
      p3: 'color(display-p3 0.13730352606790502 0.11845180023888263 0.10385234465947296)',
    },
    'sidebar-accent': {
      original: 'oklch(0.3598 0.0228 53.3857)',
      hex: '#473a32',
      p3: 'color(display-p3 0.27015523993880347 0.22934519113813445 0.20025538964003348)',
    },
    'sidebar-accent-foreground': {
      original: 'oklch(0.8018 0.0491 82.6475)',
      hex: '#cebc9b',
      p3: 'color(display-p3 0.7958949148100287 0.7396831583352622 0.6223101495452811)',
    },
    'sidebar-border': {
      original: 'oklch(0.3279 0.0144 54.0632)',
      hex: '#3b332e',
      p3: 'color(display-p3 0.22612576185990674 0.20111239351207671 0.1828776875028797)',
    },
    'sidebar-ring': {
      original: 'oklch(0.6321 0.0792 65.5619)',
      hex: '#ab8055',
      p3: 'color(display-p3 0.6447335764718548 0.5087630320683908 0.35803037831729606)',
    },
    'font-sans': 'Libre Baskerville, serif',
    'font-serif': 'Lora, serif',
    'font-mono': 'IBM Plex Mono, monospace',
    radius: 0,
    'shadow-x': 1,
    'shadow-y': -1,
    'shadow-blur': 1,
    'shadow-spread': 0,
    'shadow-opacity': '0.6',
    'shadow-color': {
      original: '#ab8055',
      hex: '#ab8055',
      p3: 'color(display-p3 0.6447217425895296 0.5087327020843586 0.3579780259637712)',
    },
    'shadow-2xs': '2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.3)',
    'shadow-xs': '2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.3)',
    'shadow-sm':
      '2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6), 2px 1px 2px -1px\n    hsl(30 33.8583% 50.1961% / 0.6)',
    shadow:
      '2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6), 2px 1px 2px -1px\n    hsl(30 33.8583% 50.1961% / 0.6)',
    'shadow-md':
      '2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6), 2px 2px 4px -1px\n    hsl(30 33.8583% 50.1961% / 0.6)',
    'shadow-lg':
      '2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6), 2px 4px 6px -1px\n    hsl(30 33.8583% 50.1961% / 0.6)',
    'shadow-xl':
      '2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 0.6), 2px 8px 10px -1px\n    hsl(30 33.8583% 50.1961% / 0.6)',
    'shadow-2xl': '2px -1px 3px 0px hsl(30 33.8583% 50.1961% / 1.5)',
  },
} as const;

export type LightTheme = typeof TOKENS.light;

/**
 * TYPE MAGIC:
 * Extracts ONLY the keys from the theme that are ColorTokens.
 * Excludes numbers (radius) and strings (fonts).
 */
export type ThemeColors = {
  [K in keyof LightTheme]: LightTheme[K] extends ColorToken ? K : never;
}[keyof LightTheme];
